import React from 'react';
import { BookCard } from '../cards/BookCard';
import { ImageList, ImageListItem } from '@mui/material';
import BookService from '../../services/BookService.js';

export const Search = ({ query }) => {

    /*const itemData = [
        {
            id: 1,
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            averageRating: 3.5,
            desciption: "Fins i tot el codi dolent pot funcionar. Però si el codi no està net, pot posar de genolls una organització de desenvolupament. Cada any es perden innombrables hores i recursos significatius a causa d'un codi mal escrit. Però no ha de ser així. Robert C. Martin, expert en software, presenta un paradigma revolucionari amb Clean Code: A Handbook of Agile Software Craftsmanship. Martin s'ha associat amb els seus col·legues d'Object Mentor per destil·lar la seva millor pràctica àgil de la neteja de codi sobre la marxa en un llibre que inculcarà dins de vostè els valors d'un artesà de programari i fer-li un millor programador però només si treballa en ell. Quin tipus de treball faràs? Vostè estarà llegint codi - un munt de codi. I se't desafiarà a pensar en el que està bé sobre aquest codi, i el que està malament amb ell. I el que és més important, se't desafiarà a reavaluar els teus valors professionals i el teu compromís amb el teu ofici. El codi net es divideix en tres parts. El primer descriu els principis, patrons i pràctiques d'escriure codi net. La segona part consta de diversos casos d'estudi de complexitat creixent. Cada cas d'estudi és un exercici de neteja de codi - de transformar una base de codi que té alguns problemes en un que és sòlid i eficient. La tercera part és la recompensa: un únic capítol que conté una llista d'heurístiques i \"malalties\" reunides mentre es crea el cas d'estudi. El resultat és una base de coneixement que descriu la manera en què pensem quan escrivim, llegim i netegem el codi. Els lectors s'allunyaran de la comprensió d'aquest llibre: - Com distingir la diferència entre codi bo i codi dolent - Com escriure un bon codi i com transformar el codi dolent en un bon codi- Com crear bons noms, bones funcions, bons objectes i bones classes - Com formatar codi per a la màxima llegibilitat - Com implementar la gestió completa d'errors sense enfosquir la lògica del codi - Com unificar test i practicar el desenvolupament basat en proves Aquest llibre és imprescindible per a qualsevol desenvolupador, enginyer de programari, gestor de projectes, cap d'equip o analista de sistemes amb interès a produir millor codi.",
            cover: 'https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF894,1000_QL80_.jpg'
        },
        {
            id: 2,
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            averageRating: 3.5,
            desciption: "Fins i tot el codi dolent pot funcionar. Però si el codi no està net, pot posar de genolls una organització de desenvolupament. Cada any es perden innombrables hores i recursos significatius a causa d'un codi mal escrit. Però no ha de ser així. Robert C. Martin, expert en software, presenta un paradigma revolucionari amb Clean Code: A Handbook of Agile Software Craftsmanship. Martin s'ha associat amb els seus col·legues d'Object Mentor per destil·lar la seva millor pràctica àgil de la neteja de codi sobre la marxa en un llibre que inculcarà dins de vostè els valors d'un artesà de programari i fer-li un millor programador però només si treballa en ell. Quin tipus de treball faràs? Vostè estarà llegint codi - un munt de codi. I se't desafiarà a pensar en el que està bé sobre aquest codi, i el que està malament amb ell. I el que és més important, se't desafiarà a reavaluar els teus valors professionals i el teu compromís amb el teu ofici. El codi net es divideix en tres parts. El primer descriu els principis, patrons i pràctiques d'escriure codi net. La segona part consta de diversos casos d'estudi de complexitat creixent. Cada cas d'estudi és un exercici de neteja de codi - de transformar una base de codi que té alguns problemes en un que és sòlid i eficient. La tercera part és la recompensa: un únic capítol que conté una llista d'heurístiques i \"malalties\" reunides mentre es crea el cas d'estudi. El resultat és una base de coneixement que descriu la manera en què pensem quan escrivim, llegim i netegem el codi. Els lectors s'allunyaran de la comprensió d'aquest llibre: - Com distingir la diferència entre codi bo i codi dolent - Com escriure un bon codi i com transformar el codi dolent en un bon codi- Com crear bons noms, bones funcions, bons objectes i bones classes - Com formatar codi per a la màxima llegibilitat - Com implementar la gestió completa d'errors sense enfosquir la lògica del codi - Com unificar test i practicar el desenvolupament basat en proves Aquest llibre és imprescindible per a qualsevol desenvolupador, enginyer de programari, gestor de projectes, cap d'equip o analista de sistemes amb interès a produir millor codi.",
            cover: 'https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF894,1000_QL80_.jpg'
        },
        {
            id: 3,
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            averageRating: 3.5,
            desciption: "Fins i tot el codi dolent pot funcionar. Però si el codi no està net, pot posar de genolls una organització de desenvolupament. Cada any es perden innombrables hores i recursos significatius a causa d'un codi mal escrit. Però no ha de ser així. Robert C. Martin, expert en software, presenta un paradigma revolucionari amb Clean Code: A Handbook of Agile Software Craftsmanship. Martin s'ha associat amb els seus col·legues d'Object Mentor per destil·lar la seva millor pràctica àgil de la neteja de codi sobre la marxa en un llibre que inculcarà dins de vostè els valors d'un artesà de programari i fer-li un millor programador però només si treballa en ell. Quin tipus de treball faràs? Vostè estarà llegint codi - un munt de codi. I se't desafiarà a pensar en el que està bé sobre aquest codi, i el que està malament amb ell. I el que és més important, se't desafiarà a reavaluar els teus valors professionals i el teu compromís amb el teu ofici. El codi net es divideix en tres parts. El primer descriu els principis, patrons i pràctiques d'escriure codi net. La segona part consta de diversos casos d'estudi de complexitat creixent. Cada cas d'estudi és un exercici de neteja de codi - de transformar una base de codi que té alguns problemes en un que és sòlid i eficient. La tercera part és la recompensa: un únic capítol que conté una llista d'heurístiques i \"malalties\" reunides mentre es crea el cas d'estudi. El resultat és una base de coneixement que descriu la manera en què pensem quan escrivim, llegim i netegem el codi. Els lectors s'allunyaran de la comprensió d'aquest llibre: - Com distingir la diferència entre codi bo i codi dolent - Com escriure un bon codi i com transformar el codi dolent en un bon codi- Com crear bons noms, bones funcions, bons objectes i bones classes - Com formatar codi per a la màxima llegibilitat - Com implementar la gestió completa d'errors sense enfosquir la lògica del codi - Com unificar test i practicar el desenvolupament basat en proves Aquest llibre és imprescindible per a qualsevol desenvolupador, enginyer de programari, gestor de projectes, cap d'equip o analista de sistemes amb interès a produir millor codi.",
            cover: 'https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF894,1000_QL80_.jpg'
        },
        {
            id: 4,
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            averageRating: 3.5,
            desciption: "Fins i tot el codi dolent pot funcionar. Però si el codi no està net, pot posar de genolls una organització de desenvolupament. Cada any es perden innombrables hores i recursos significatius a causa d'un codi mal escrit. Però no ha de ser així. Robert C. Martin, expert en software, presenta un paradigma revolucionari amb Clean Code: A Handbook of Agile Software Craftsmanship. Martin s'ha associat amb els seus col·legues d'Object Mentor per destil·lar la seva millor pràctica àgil de la neteja de codi sobre la marxa en un llibre que inculcarà dins de vostè els valors d'un artesà de programari i fer-li un millor programador però només si treballa en ell. Quin tipus de treball faràs? Vostè estarà llegint codi - un munt de codi. I se't desafiarà a pensar en el que està bé sobre aquest codi, i el que està malament amb ell. I el que és més important, se't desafiarà a reavaluar els teus valors professionals i el teu compromís amb el teu ofici. El codi net es divideix en tres parts. El primer descriu els principis, patrons i pràctiques d'escriure codi net. La segona part consta de diversos casos d'estudi de complexitat creixent. Cada cas d'estudi és un exercici de neteja de codi - de transformar una base de codi que té alguns problemes en un que és sòlid i eficient. La tercera part és la recompensa: un únic capítol que conté una llista d'heurístiques i \"malalties\" reunides mentre es crea el cas d'estudi. El resultat és una base de coneixement que descriu la manera en què pensem quan escrivim, llegim i netegem el codi. Els lectors s'allunyaran de la comprensió d'aquest llibre: - Com distingir la diferència entre codi bo i codi dolent - Com escriure un bon codi i com transformar el codi dolent en un bon codi- Com crear bons noms, bones funcions, bons objectes i bones classes - Com formatar codi per a la màxima llegibilitat - Com implementar la gestió completa d'errors sense enfosquir la lògica del codi - Com unificar test i practicar el desenvolupament basat en proves Aquest llibre és imprescindible per a qualsevol desenvolupador, enginyer de programari, gestor de projectes, cap d'equip o analista de sistemes amb interès a produir millor codi.",
            cover: 'https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF894,1000_QL80_.jpg'
        },
        {
            id: 5,
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            averageRating: 3.5,
            desciption: "Fins i tot el codi dolent pot funcionar. Però si el codi no està net, pot posar de genolls una organització de desenvolupament. Cada any es perden innombrables hores i recursos significatius a causa d'un codi mal escrit. Però no ha de ser així. Robert C. Martin, expert en software, presenta un paradigma revolucionari amb Clean Code: A Handbook of Agile Software Craftsmanship. Martin s'ha associat amb els seus col·legues d'Object Mentor per destil·lar la seva millor pràctica àgil de la neteja de codi sobre la marxa en un llibre que inculcarà dins de vostè els valors d'un artesà de programari i fer-li un millor programador però només si treballa en ell. Quin tipus de treball faràs? Vostè estarà llegint codi - un munt de codi. I se't desafiarà a pensar en el que està bé sobre aquest codi, i el que està malament amb ell. I el que és més important, se't desafiarà a reavaluar els teus valors professionals i el teu compromís amb el teu ofici. El codi net es divideix en tres parts. El primer descriu els principis, patrons i pràctiques d'escriure codi net. La segona part consta de diversos casos d'estudi de complexitat creixent. Cada cas d'estudi és un exercici de neteja de codi - de transformar una base de codi que té alguns problemes en un que és sòlid i eficient. La tercera part és la recompensa: un únic capítol que conté una llista d'heurístiques i \"malalties\" reunides mentre es crea el cas d'estudi. El resultat és una base de coneixement que descriu la manera en què pensem quan escrivim, llegim i netegem el codi. Els lectors s'allunyaran de la comprensió d'aquest llibre: - Com distingir la diferència entre codi bo i codi dolent - Com escriure un bon codi i com transformar el codi dolent en un bon codi- Com crear bons noms, bones funcions, bons objectes i bones classes - Com formatar codi per a la màxima llegibilitat - Com implementar la gestió completa d'errors sense enfosquir la lògica del codi - Com unificar test i practicar el desenvolupament basat en proves Aquest llibre és imprescindible per a qualsevol desenvolupador, enginyer de programari, gestor de projectes, cap d'equip o analista de sistemes amb interès a produir millor codi.",
            cover: 'https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF894,1000_QL80_.jpg'
        },
        {
            id: 6,
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            averageRating: 3.5,
            desciption: "Fins i tot el codi dolent pot funcionar. Però si el codi no està net, pot posar de genolls una organització de desenvolupament. Cada any es perden innombrables hores i recursos significatius a causa d'un codi mal escrit. Però no ha de ser així. Robert C. Martin, expert en software, presenta un paradigma revolucionari amb Clean Code: A Handbook of Agile Software Craftsmanship. Martin s'ha associat amb els seus col·legues d'Object Mentor per destil·lar la seva millor pràctica àgil de la neteja de codi sobre la marxa en un llibre que inculcarà dins de vostè els valors d'un artesà de programari i fer-li un millor programador però només si treballa en ell. Quin tipus de treball faràs? Vostè estarà llegint codi - un munt de codi. I se't desafiarà a pensar en el que està bé sobre aquest codi, i el que està malament amb ell. I el que és més important, se't desafiarà a reavaluar els teus valors professionals i el teu compromís amb el teu ofici. El codi net es divideix en tres parts. El primer descriu els principis, patrons i pràctiques d'escriure codi net. La segona part consta de diversos casos d'estudi de complexitat creixent. Cada cas d'estudi és un exercici de neteja de codi - de transformar una base de codi que té alguns problemes en un que és sòlid i eficient. La tercera part és la recompensa: un únic capítol que conté una llista d'heurístiques i \"malalties\" reunides mentre es crea el cas d'estudi. El resultat és una base de coneixement que descriu la manera en què pensem quan escrivim, llegim i netegem el codi. Els lectors s'allunyaran de la comprensió d'aquest llibre: - Com distingir la diferència entre codi bo i codi dolent - Com escriure un bon codi i com transformar el codi dolent en un bon codi- Com crear bons noms, bones funcions, bons objectes i bones classes - Com formatar codi per a la màxima llegibilitat - Com implementar la gestió completa d'errors sense enfosquir la lògica del codi - Com unificar test i practicar el desenvolupament basat en proves Aquest llibre és imprescindible per a qualsevol desenvolupador, enginyer de programari, gestor de projectes, cap d'equip o analista de sistemes amb interès a produir millor codi.",
            cover: 'https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF894,1000_QL80_.jpg'
        },
        {
            id: 7,
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            averageRating: 3.5,
            desciption: "Fins i tot el codi dolent pot funcionar. Però si el codi no està net, pot posar de genolls una organització de desenvolupament. Cada any es perden innombrables hores i recursos significatius a causa d'un codi mal escrit. Però no ha de ser així. Robert C. Martin, expert en software, presenta un paradigma revolucionari amb Clean Code: A Handbook of Agile Software Craftsmanship. Martin s'ha associat amb els seus col·legues d'Object Mentor per destil·lar la seva millor pràctica àgil de la neteja de codi sobre la marxa en un llibre que inculcarà dins de vostè els valors d'un artesà de programari i fer-li un millor programador però només si treballa en ell. Quin tipus de treball faràs? Vostè estarà llegint codi - un munt de codi. I se't desafiarà a pensar en el que està bé sobre aquest codi, i el que està malament amb ell. I el que és més important, se't desafiarà a reavaluar els teus valors professionals i el teu compromís amb el teu ofici. El codi net es divideix en tres parts. El primer descriu els principis, patrons i pràctiques d'escriure codi net. La segona part consta de diversos casos d'estudi de complexitat creixent. Cada cas d'estudi és un exercici de neteja de codi - de transformar una base de codi que té alguns problemes en un que és sòlid i eficient. La tercera part és la recompensa: un únic capítol que conté una llista d'heurístiques i \"malalties\" reunides mentre es crea el cas d'estudi. El resultat és una base de coneixement que descriu la manera en què pensem quan escrivim, llegim i netegem el codi. Els lectors s'allunyaran de la comprensió d'aquest llibre: - Com distingir la diferència entre codi bo i codi dolent - Com escriure un bon codi i com transformar el codi dolent en un bon codi- Com crear bons noms, bones funcions, bons objectes i bones classes - Com formatar codi per a la màxima llegibilitat - Com implementar la gestió completa d'errors sense enfosquir la lògica del codi - Com unificar test i practicar el desenvolupament basat en proves Aquest llibre és imprescindible per a qualsevol desenvolupador, enginyer de programari, gestor de projectes, cap d'equip o analista de sistemes amb interès a produir millor codi.",
            cover: 'https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF894,1000_QL80_.jpg'
        },
    ];*/

    const [results, setResults] = React.useState([]);

    React.useEffect(() => {
        if (query) {
            BookService.getGoogleBooksByQuery(query).then((response) => {
                console.log(response.data.items);
                setResults(response.data.items);
            });
        }
      }, [query]); // Se ejecuta cada vez que query cambia

    return (
        <ImageList sx={{ width: '100%', height: '100%', padding: '1rem', margin: 0 }} cols={3} gap={20}>
        {results.map((item) => (
            <ImageListItem key={item.id}>
            <BookCard bookData={ item } />
            </ImageListItem>
        ))}
        </ImageList>
    );
}