name: Run Tests and Coverage

on:
  pull_request:
    branches:
      - development

  push:
    branches:
      - development

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    env:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: localhost
      DB_PORT: 5432

      DB_NAME: db

      DB_NAME_TEST: db_test

      ALGORITHM: HS256
      SECRET_KEY: your_secret_key

      ENVIRONMENT: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r UBReads_backend/requirements.txt

    - name: Run tests with coverage
      run: |
        python -m coverage run -m pytest
        python -m coverage report
        python -m coverage xml

    - name: Show coverage report
  run: |
    coverage report

