name: Run Tests and Coverage

on:
  pull_request:
    branches:
      - development

  push:
    branches:
      - development

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/upload-artifact@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Ajusta la versión según tus necesidades

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        python -m coverage run -m pytest
        python -m coverage report
        python -m coverage xml

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
