name: CI/CD for UBReads Backend

on:
  push:
    branches:
      - main
      - preproduction

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "BACKEND_IP=3.255.70.190" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=preproduction" >> $GITHUB_ENV
          echo "BACKEND_IP=34.246.34.123" >> $GITHUB_ENV
        fi

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Crear el archivo .pem basado en secretos para acceder a EC2
    - name: Crear archivo .pem y .env desde secret
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
        else
          echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem          
        fi
    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        echo "${{ secrets.AWS_REGION }}"
        echo "docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    
    # Build, tag, and push Docker image
    - name: Build Docker Image
      run: docker build -t ubreads-backend ./UBReads_backend

    - name: Tag Docker Image
      run: docker tag ubreads-backend:latest 381492053763.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ubreads-repo:${{ env.ENVIRONMENT }}

    - name: Push Docker Image to ECR
      run: docker push 381492053763.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ubreads-repo:${{ env.ENVIRONMENT }}

    # Deploy the backend to EC2
    - name: Deploy Backend to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ env.BACKEND_IP }} << 'EOF'
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export DB_HOST=${{ secrets.DB_HOST }}
        export DB_NAME=${{ secrets.DB_NAME }}
        export DB_PORT=${{ secrets.DB_PORT }}
        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        export ALGORITHM=HS256  
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        docker-compose pull
        docker-compose up -d
        EOF
