name: Build and Push to Docker Hub

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest ./UBReads_backend
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest ./UBReads_frontend
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restart Azure App Service
      run: |
        az webapp restart --name UBReads --resource-group UB-ES-2024-C2