name: Deploy Database

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy-database:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Create Database (if not exists)
      env:
        DB_USER: ${{ secrets.AZURE_DB_USER }}
        DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
        DB_HOST: ${{ secrets.AZURE_DB_HOST }}
        DB_NAME: ${{ secrets.AZURE_DB_NAME }}
        DB_PORT: ${{ secrets.AZURE_DB_PORT }}
      run: |
        psql "postgresql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/postgres" \
        -c "CREATE DATABASE $DB_NAME;" || echo "Database already exists"

    - name: Migrate Tables
      env:
        DB_USER: ${{ secrets.AZURE_DB_USER }}
        DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
        DB_HOST: ${{ secrets.AZURE_DB_HOST }}
        DB_NAME: ${{ secrets.AZURE_DB_NAME }}
        DB_PORT: ${{ secrets.AZURE_DB_PORT }}
      run: |
        cd UBReads_backend
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
        python -c "from app.core.database import create_tables; create_tables()"
