# name: Deploy Combined App
# 
# on:
#   pull_request:
#     types: [closed]
#     branches: [main]
# 
# jobs:
#   deploy:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
# 
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '16'
# 
#     - name: Build Frontend
#       working-directory: ./UBReads_frontend
#       run: |
#         npm install
#         npm run build
# 
#     - name: Copy Frontend Build to Backend
#       run: cp -r ./UBReads_frontend/dist ./UBReads_backend/
# 
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.12'
# 
#     - name: Install Backend dependencies
#       working-directory: ./UBReads_backend
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
# 
#     - name: Deploy to Azure Web App
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: "ubreads"
#         publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
#         package: ./UBReads_backend
