name: Run End to End tests

on:
  pull_request:
    branches:
      - sprint3/qa/test/end2end-tests
      - development
  push:
    branches:
      - sprint3/qa/test/end2end-tests
      - development

jobs:
  cypress-run:
    name: Run Cypress End-to-End Tests
    runs-on: ubuntu-latest

    env:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: db
      DB_NAME_TEST: db_test
      ALGORITHM: HS256
      SECRET_KEY: your_secret_key
      ENVIRONMENT: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r UBReads_backend/requirements.txt
          cd UBReads_frontend 
          npm install

      - name: Start application server
        run: |
          cd UBReads_frontend
          npm run dev & 
          npx wait-on http://localhost:5173
          cd ..
          cd UBReads_backend
          python -m uvicorn main:app --reload &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run
          wait-on: http://localhost:5173 # Waits for server to respond

      - name: Upload Cypress Screenshots & Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
